### ISSUE TITLE
Grouping components

### ISSUE THREAD

**Issue by matthuszagh** [circuitikz/circuitikz#263]
Is it possible to create groups of components and then refer to and interconnect those groups? It would be great to be able to specify anchors that can make connections as well. Is there a good way to do this? Judging by [this issue](https://github.com/circuitikz/circuitikz/issues/6) maybe not, but this would be a really great feature. Using `pic`s or `pgfooclass` from tikz/pgf I guess could be made to achieve a similar effect, but the integration doesn't feel that seemless. Thoughts on how best to achieve this and/or whether this would be a desired feature in circuitikz?

**Comment by Rmano** [comment]
Not directly; I normally use relative coordinates to define circuits blocks, with coordinates, and then embed them in `\def`s. This allows only translations but for my use of circuits they are all what I need. I can post an example later if you think is worthwhile. 

The problems are more the ones caused by #211 (which reflects on #146) than your cited issue - - - #6 can probably be solved with the `fit` library.

**Comment by matthuszagh** [comment]
An example would be useful, thanks. And I was unaware of `fit`, looks like it could be useful, thanks for mentioning that.

**Comment by Rmano** [comment]
I normally do things like this: 

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\def\buffer(#1){%
    node[op amp, anchor=+](BUF#1){oa#1}
    (BUF#1.-) -- ++(0,1) -| (BUF#1.out)
}

\begin{circuitikz}[
    ]
    \draw (0,0) \buffer(1);
    \draw (BUF1.out) -- ++(1,0) \buffer(2);
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/62820075-4a0a7f80-bb5f-11e9-9d36-1c067e1601a0.png)

**Comment by matthuszagh** [comment]
Thanks!

**Comment by matthuszagh** [comment]
Is there a way to do this with custom nodes but without editing a circuitikz file (by defining it directly in the main source file)? It seems like the solution above has some limitations/nodes have greater flexibility. For instance, if I wanted to define a multi-port network and then reference it, it would be useful to be able to refer to the network's ports (e.g., in the same way that a BJT has B, C, E anchors).

To give a concrete example, I've frequently found myself replacing a transistor in a circuit with a small-signal equivalent circuit. It would be great to be able to use the small-signal equivalent circuit as a drop-in replacement for the transistor. An alternative is to define this small-signal circuit in circuitikz, but I'm not sure it warrants inclusion. Moreover, there are other cases where I'd want a subcircuit that is very specific and wouldn't make sense to include in circuitikz.

**Comment by Rmano** [comment]
You can mimic a node behavior with a macro quite well --- the only thing missing is the `anchor=` ability (notice that the same happens with `pic`s --- although the point is moot, because `circuitikz` path-style `to` does not work in pics). 

In the example above, you can access internal nodes --- just use `(BUF1.up)` for example. It is surely possible to write a couple of macros that put a BJT or its equivalent (for a rapid switch) given that you do not change the anchor... and that you allow for the extra space when drawing the BJT.
