### ISSUE TITLE
battery poles not swapped when using invert option

### ISSUE THREAD

**Issue by SergioGonzalezSevilla** [circuitikz/circuitikz#55]
Hi,

if I use option 'invert' with a battery component, the terminal polarities remain unchanged, while for consistency, I think they should be swapped...
[bat_invert.pdf](https://github.com/circuitikz/circuitikz/files/606348/bat_invert.pdf)

**Comment by sistlind** [comment]
Hi,
this is intended, because the battery behaves like a voltage source. To invert it, just invert the voltage direction by v<=1V and v>=1V, respectively.

I dont want to include the invert command for the sources, because there are already a lot of if-else-conditions and the code is really ugly at this point :/
