### ISSUE TITLE
Draw straight arrows for voltage instead of incurved

### ISSUE THREAD

**Issue by thejoker2** [circuitikz/circuitikz#56]
In France (and I guess most of Europe) voltage arrows next to the dipole are straight, not incurved.

Would it be possible to replace incurved arrow by straight arrows?

Up to now, everybody has to draw arrows separately next to each dipole, which is quite time-consuming, and it removes the interest of the package.

Thanks a lot for all of us!

**Comment by thejoker2** [comment]
Sorry, I've been just told that the "straightvoltages" option exists.
`\usepackage[european,straightvoltages]{circuitikz}`

But unfortunately the result is not as good as expected, by far:

![image](https://cloud.githubusercontent.com/assets/24369435/20868042/317691e2-ba28-11e6-8bd5-bfecdbb3ed6a.png)
![image](https://cloud.githubusercontent.com/assets/24369435/20868071/9ec4f734-ba28-11e6-9ab4-71c3350ddf51.png)

**Comment by sistlind** [comment]
Hi,
the straighvoltages are only in alpha-testing, because it is very complicated to auto-position the label and the arrow. It should look better if you use a much larger schematic. Nevertheless, there are a few bugs left(e.g. u_7). Alternatively, just name the node and create the voltage arrows by hand afterwards(This is the way i draw my schematics).

Btw: This seems to be only the correct way in france. Accourding DIN EN 60375:2004 and  IEC 60050 the implemented directions are correct (see https://de.wikipedia.org/wiki/Z%C3%A4hlpfeil (sorry, found it only in german))

Best regards,
Stefan
