### ISSUE TITLE
[Bug] Incorrect documentation of resistor

### ISSUE THREAD

**Issue by quark67** [circuitikz/circuitikz#765]
**Describe the bug**
The manual show how to change the height of the resistor, but the text say that we "can change the width of resistor, **not the height**".

**To Reproduce**
Open the manual on page 37, which show how to change the **height**.

**Screenshots**
<img width="1001" alt="image" src="https://github.com/circuitikz/circuitikz/assets/9338576/d2c771da-5981-40d5-bef8-b84b50bb76d3">

**But in fact (with this modified code example)**

We can change the width AND the height (but only on "american" resistor, not "european"): 

```latex
\begin{circuitikz}[american]
\tikz \draw (0,0) to[R=1<\ohm>] (2,0); 
\ctikzset{bipoles/resistor/width=3.5, bipoles/resistor/height=.6}
\tikz \draw (0,0) to[R=1<\ohm>] (5.5,0);
\end{circuitikz}
```

gives:

<img width="436" alt="image" src="https://github.com/circuitikz/circuitikz/assets/9338576/e382b2e1-b67f-4726-a3a9-a913f0dab7f9">

**Operating system, LaTeX distribution**

Version 1.6.6 of circuitikz

**Expected behavior**

Modifying the manual with an example showing that the width and the heigth of the resistor can be changed AND a code which show that.

**Comment by Rmano** [comment]
Well, the problem is really the example on page 37, which I should remove. As you noticed, it works only for American resistors (you have to use the internal name of the European one, `generic`, to change it), so basically, it is accessing internal parameters, which I do not want to be forced to maintain forever(*). So I will change the docs, but probably not in the way you think... 😉

To change the resistors' width and height, you should change the scale and width locally, which will work for every style. 

For example, using styles:

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[siunitx]{circuitikz}
\begin{document}
    \ctikzset{american}
    \tikz \draw (0,0) to[R=1<\ohm>] (4,0);

    \ctikzset{bigR/.style={resistors/scale=4, resistors/width=1}}
    \tikz \draw (0,0) to[R=1<\ohm>, bigR] (6,0);

    \ctikzset{european}
    \tikz \draw (0,0) to[R=1<\ohm>, bigR] (6,0);

\end{document}
```

![image](https://github.com/circuitikz/circuitikz/assets/6414907/20d3dd42-0635-4f00-b175-55b8a615f646)


BTW, your code is wrong; you are nesting Ti*k*Z environment using `\tikz`inside `circuitikz`.  See https://tex.stackexchange.com/questions/46598/problem-with-overlay-when-a-tikzpicture-is-inside-another-tikzpicture for example

(*) if you look at the source, there are *thousands* of parameter that are all the same (for example, widths for every type of resistor or source or...), which I would like to get rid of when I have time, and putting it in the manual is a form of officially freeze them forever.

**Comment by Rmano** [comment]
Like this:

\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[siunitx]{circuitikz}
\begin{document}
    \ctikzset{american}
    \tikz \draw (0,0) to[R=1<\ohm>] (4,0);

    \ctikzset{bigR/.style={resistors/scale=4, resistors/width=1}}
    \tikz \draw (0,0) to[R=1<\ohm>, bigR] (6,0);

    \ctikzset{european}
    \tikz \draw (0,0) to[R=1<\ohm>, bigR] (6,0);

\end{document}

**Comment by quark67** [comment]
> BTW, your code is wrong; you are nesting TikZ environment using `\tikz` inside `circuitikz`. 

Yes, right, my bad.

I loaded the package with `\usepackage[siunitx,europeanresistors]{circuitikz}` in order to have the european shape for resistor (**as an European, the european resistor shape seems so natural...**).

In first attempt, I only used the code:

```latex
\tikz \draw (0,0) to[R=1<\ohm>] (2,0); 
\ctikzset{bipoles/resistor/width=3.5, bipoles/resistor/height=.6}
\tikz \draw (0,0) to[R=1<\ohm>] (5.5,0);
```

and to quickly obtain the american shape, I enclosed this previous code with `\begin{circuitikz}[american]` ... `\end{circuitikz}`, which is in fact an error as you pointed out. The 2 `\tikz` are superfluous. And in fact, using `\ctikzset{american}` is effectively more quick.

Thanks.
