### ISSUE TITLE
[New Component] Transient generator

### ISSUE THREAD

**Issue by jmonclard** [circuitikz/circuitikz#809]
Idea for a future release : a source with an inner symbol representing transient waveform. Would be of interest in schematics and drawings relative to device EMC qualification tests (indirect lightning surge, ESD, electrical fast transient burst,...).

Typical waveforms used in industrial/aeronautic/military applications include unipolar and damped sinusoid. So two different symbols would be nice.

Such tests are for instance defined in IEC EN 61000-4 standards (61000-4-2, 61000-4-5, 61000-4-4)

**Example of usage in a specification document for aero applications**

![transient](https://github.com/circuitikz/circuitikz/assets/15088398/37e86456-2ea6-4eeb-ac44-f9abfcf8938b)

**Example of symbol used in LT Spice circuit simulator**
![LTspice](https://github.com/circuitikz/circuitikz/assets/15088398/29f89651-35da-47c5-85b9-ae719722a777)

**Hand drawing example of a damped sinusoid generator symbol**
![IdeaOfDampedSinusoid](https://github.com/circuitikz/circuitikz/assets/15088398/7452e0cd-2efc-47ad-9bc3-d5e4bf10c665)

**Comment by Rmano** [comment]
Hm... I do not know if that one is really needed. Those are typically one-shot components, in the sense that you have an off-one in a circuit, so it can be easily built by drawing on an empty source.

```latex
\documentclass[border=3mm]{standalone}
\usepackage{circuitikz}
\newcommand{\addVpulse}[1]{%
    \draw (#1.center) ++(-0.3,-0.2) -- ++(0.1,0) -- ++(0,0.4)
        to[bend right] ++(0.4,-0.4) -- ++(0.1,0);
    }
\begin{document}
\begin{circuitikz}
    \draw (0,0) to[esource, v=$V_p$, name=vp] ++(0,2);
    \addVpulse{vp}
\end{circuitikz}
\end{document}
```

![image](https://github.com/circuitikz/circuitikz/assets/6414907/0af46829-eb8c-4472-bb94-8b9b27a23c68)

An option could be to add some mechanism for including arbitrary drawings to a source so that we can define a style similar to what is done for oscilloscopes (Look for "Oscilloscope waveform" in the manual, around page 81)

**Comment by Rmano** [comment]
I will close this for now --- please feel free to reopen if you think it is not answered!
